name: Test Coverage
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  report-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.5
      - name: Run tests
        run: |
          CI=true bundle exec rake specs:env
      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key ruby --value-file coverage/.resultset.json

        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
