  - uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  - name: Report results to DeepSource
    run: |
    # Run tests and generate simplecov coverage
      bundle exec rspec

    # Install deepsource CLI
      curl https://deepsource.io/cli | sh

    # From the root directory, run the report coverage command
      ./bin/deepsource report --analyzer test-coverage --key ruby --value-file coverage/.resultset.json

    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
